markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title.html
name: "courage future"
markdown: rdiscount

author: "yangyt"
atom-baseurl: "https://meishiguang.github.io"
disqus: "meishiguang3"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Gallery
    class: fa fa-film
    href: http://instagram.com/meishiguang
  - title: Blogroll
    class: fa fa-link
    href: /links.html
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

